/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatieprogramma.ui;

import java.awt.CardLayout;

/**
 *
 * @author Mettuh
 */
public class StartScherm extends javax.swing.JFrame {

    /**
     * Creates new form StartScherm
     */
    public StartScherm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nieuweOfferteButton = new javax.swing.JButton();
        calculatiesButton = new javax.swing.JButton();
        inUitvoeringButton = new javax.swing.JButton();
        onverkochtButton = new javax.swing.JButton();
        opgeleverdButton = new javax.swing.JButton();
        inhoudsPanel = new javax.swing.JPanel();
        leegPanel = new javax.swing.JPanel();
        nieuweOffertePanel = new javax.swing.JPanel();
        werfadresInput = new javax.swing.JTextField();
        adresBouwheerInput2 = new javax.swing.JTextField();
        faxInput = new javax.swing.JTextField();
        werfnaamInput = new javax.swing.JTextField();
        telInput = new javax.swing.JTextField();
        gsmInput = new javax.swing.JTextField();
        adresBouwheerInput = new javax.swing.JTextField();
        btwInput = new javax.swing.JTextField();
        bouwheerInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        annuleerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firmanaamInput = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculatieprogramma");

        nieuweOfferteButton.setText("Nieuwe Offerte");
        nieuweOfferteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nieuweOfferteButtonActionPerformed(evt);
            }
        });

        calculatiesButton.setText("Calculaties");

        inUitvoeringButton.setText("In Uitvoering");

        onverkochtButton.setText("Onverkocht");

        opgeleverdButton.setText("Opgeleverd");

        inhoudsPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout leegPanelLayout = new javax.swing.GroupLayout(leegPanel);
        leegPanel.setLayout(leegPanelLayout);
        leegPanelLayout.setHorizontalGroup(
            leegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        leegPanelLayout.setVerticalGroup(
            leegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        inhoudsPanel.add(leegPanel, "leegPanel");

        nieuweOffertePanel.setName("nieuweOfferte");

        jLabel2.setText("Bouwheer:");

        jLabel9.setText("Werfadres:");

        jLabel6.setText("GSM:");

        jLabel5.setText("Tel:");

        jLabel4.setText("BTW:");

        jLabel3.setText("Adres van de bouwheer:");

        jLabel8.setText("Werfnaam:");

        jLabel7.setText("FAX:");

        okButton.setText("OK");

        annuleerButton.setText("Annuleer");
        annuleerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuleerButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Firmanaam:");

        javax.swing.GroupLayout nieuweOffertePanelLayout = new javax.swing.GroupLayout(nieuweOffertePanel);
        nieuweOffertePanel.setLayout(nieuweOffertePanelLayout);
        nieuweOffertePanelLayout.setHorizontalGroup(
            nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nieuweOffertePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nieuweOffertePanelLayout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(annuleerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bouwheerInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adresBouwheerInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btwInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gsmInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(faxInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(werfnaamInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(werfadresInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firmanaamInput)
                    .addComponent(adresBouwheerInput2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(88, 88, 88))
        );
        nieuweOffertePanelLayout.setVerticalGroup(
            nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nieuweOffertePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firmanaamInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bouwheerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adresBouwheerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(adresBouwheerInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btwInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gsmInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(faxInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(werfnaamInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(werfadresInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nieuweOffertePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(annuleerButton))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        inhoudsPanel.add(nieuweOffertePanel, "nieuweOfferte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        inhoudsPanel.add(jPanel1, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onverkochtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opgeleverdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nieuweOfferteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculatiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inUitvoeringButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inhoudsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inhoudsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nieuweOfferteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculatiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inUitvoeringButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(onverkochtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opgeleverdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nieuweOfferteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nieuweOfferteButtonActionPerformed
        CardLayout cl = (CardLayout) inhoudsPanel.getLayout();
        cl.show(inhoudsPanel, "nieuweOfferte");
    }//GEN-LAST:event_nieuweOfferteButtonActionPerformed

    private void annuleerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuleerButtonActionPerformed
        CardLayout cl = (CardLayout) inhoudsPanel.getLayout();
        cl.show(inhoudsPanel, "leegPanel");
    }//GEN-LAST:event_annuleerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StartScherm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresBouwheerInput;
    private javax.swing.JTextField adresBouwheerInput2;
    private javax.swing.JButton annuleerButton;
    private javax.swing.JTextField bouwheerInput;
    private javax.swing.JTextField btwInput;
    private javax.swing.JButton calculatiesButton;
    private javax.swing.JTextField faxInput;
    private javax.swing.JTextField firmanaamInput;
    private javax.swing.JTextField gsmInput;
    private javax.swing.JButton inUitvoeringButton;
    private javax.swing.JPanel inhoudsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leegPanel;
    private javax.swing.JButton nieuweOfferteButton;
    private javax.swing.JPanel nieuweOffertePanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton onverkochtButton;
    private javax.swing.JButton opgeleverdButton;
    private javax.swing.JTextField telInput;
    private javax.swing.JTextField werfadresInput;
    private javax.swing.JTextField werfnaamInput;
    // End of variables declaration//GEN-END:variables
}
